---

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3072m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

      - run: ./gradlew build ktlintCheck test

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs

      - store_artifacts:
          path: build/reports